server:
  port: 80
eureka:
  client:
    register-with-eureka: false    #表识不向注册中心注册自己
    #fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。

ribbon:
  #方法调用处理时间
  ReadTimeout: 6000
  #连接时间
  ConnectTimeout: 6000

#超时时间配置，此处全局超时配置时间大于@HystrixProperty配置时间后，@HystrixProperty注解中的超时才生效
#此处神坑，需注意，视频中未提到该点
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000